"""Pure-Python metrics & progression module for the Anomaly Engine pipeline.

Computes per-run metrics from the existing JSONL phase outputs and run log,
emits a per-run snapshot, and appends to the cross-run timeline. Runs at the
end of `_run_formatter` (no extra LLM calls).

Design rules:
- MUST NOT import openrouter_client, anthropic, or httpx (mirror ANOMALY-001).
- Pure file I/O + arithmetic. Reads existing data/{0X}*.jsonl files.
- All durability via pipeline.state.safe_write / append_jsonl (ADR-0001).

Outputs:
    data/metrics/{run_id}.json           per-run snapshot
    data/metrics/timeline.jsonl          append-only cross-run history
    docs/PROGRESSION.md                  human-readable trend (regenerated by `make metrics`)
"""

from __future__ import annotations

import datetime
import json
from pathlib import Path
from typing import Any

from pipeline.state import append_jsonl, safe_write

# ── Paths ────────────────────────────────────────────────────────────────────

_DATA_DIR = Path("data")
_METRICS_DIR = _DATA_DIR / "metrics"
_TIMELINE_PATH = _METRICS_DIR / "timeline.jsonl"
_RUN_LOG = _DATA_DIR / "run_log.jsonl"
_OUT_DIR = Path("out") / "concepts"
_PROGRESSION_PATH = Path("docs") / "PROGRESSION.md"

_PHASE_FILES: dict[str, Path] = {
    "miner": _DATA_DIR / "01_assets.jsonl",
    "mapper": _DATA_DIR / "02_jtbd.jsonl",
    "validator": _DATA_DIR / "03_audience.jsonl",
    "forger": _DATA_DIR / "04_concepts.jsonl",
    "critic": _DATA_DIR / "05_critiques.jsonl",
}

_STAB_QUEUE = _DATA_DIR / "stabilization_queue.jsonl"

_PRODUCTION_FLOOR: int = 85
_DELTA_MIN_RUNS: int = 2

# ── Public API ───────────────────────────────────────────────────────────────


def compute_run_metrics(
    run_id: str,
    theme: str,
    model: str,
    format_floor: float = float(_PRODUCTION_FLOOR),
) -> dict[str, Any]:
    """Compute the full metric snapshot for a single pipeline run.

    Args:
        run_id: Session UUID (orchestrator-assigned).
        theme: The theme passed to the miner.
        model: The model identifier used for LLM calls.
        format_floor: The score floor the formatter used to publish (CLI flag).
                      Persisted so evals can verify "every published concept
                      meets the floor that was configured for its run."

    Returns:
        Dict with all metric categories. Structure is stable; missing data
        becomes 0 / 0.0 / [] rather than KeyError.
    """
    asset_count = _count_jsonl_rows(_PHASE_FILES["miner"])
    jtbd_count = _count_jsonl_rows(_PHASE_FILES["mapper"])
    audience_count = _count_jsonl_rows(_PHASE_FILES["validator"])
    concept_count = _count_jsonl_rows(_PHASE_FILES["forger"])
    critique_count = _count_jsonl_rows(_PHASE_FILES["critic"])

    final_scores = _read_final_scores(_PHASE_FILES["critic"])
    published_ids = _published_concept_ids()

    domain_dist = _domain_distribution(_PHASE_FILES["miner"])

    cost_usd = _sum_run_log_cost(run_id)
    wall_times = _wall_time_per_phase(run_id)
    key_rotations = _count_key_rotations(run_id)
    stab_count = _count_stabilization_queued(run_id)

    return {
        "run_id": run_id,
        "ts": datetime.datetime.now(datetime.UTC).isoformat(),
        "theme": theme,
        "model": model,
        "format_floor": float(format_floor),
        # A. Phase output volume
        "asset_count": asset_count,
        "jtbd_count": jtbd_count,
        "audience_count": audience_count,
        "concept_count": concept_count,
        "critique_count": critique_count,
        "concept_published_count": len(published_ids),
        # B. Quality
        "concept_final_score_p50": _percentile(final_scores, 50),
        "concept_final_score_max": max(final_scores) if final_scores else 0,
        "concept_final_score_mean": (
            round(sum(final_scores) / len(final_scores), 1) if final_scores else 0
        ),
        "concepts_passing_85_pure_critic_count": sum(
            1 for s in final_scores if s >= _PRODUCTION_FLOOR
        ),
        # C. Diversity
        "asset_domain_distribution": domain_dist,
        "asset_domain_count": len(domain_dist),
        # D. Stabilization loop
        "stabilization_patterns_queued": stab_count,
        # E. Cost & latency
        "total_cost_usd_per_run": round(cost_usd, 4),
        "cost_per_published_concept_usd": round(cost_usd / max(len(published_ids), 1), 4),
        "wall_time_per_phase_s": wall_times,
        "key_rotation_count": key_rotations,
    }


def emit_metrics(snapshot: dict[str, Any]) -> None:
    """Write the per-run snapshot AND append to the cross-run timeline."""
    _METRICS_DIR.mkdir(parents=True, exist_ok=True)
    snapshot_path = _METRICS_DIR / f"{snapshot['run_id']}.json"
    safe_write(snapshot_path, json.dumps(snapshot, indent=2) + "\n")
    append_jsonl(_TIMELINE_PATH, snapshot)


def regenerate_progression_md() -> str:
    """Rebuild docs/PROGRESSION.md from data/metrics/timeline.jsonl. Returns the new content."""
    rows = _read_timeline()
    if not rows:
        body = "No runs recorded yet — run the pipeline at least once.\n"
    else:
        body = _build_progression_body(rows)
    content = (
        "# Anomaly Engine — Progression Report\n\n"
        f"Auto-generated from `data/metrics/timeline.jsonl` "
        f"on {datetime.datetime.now(datetime.UTC).isoformat()}.\n"
        f"Total runs: **{len(rows)}**.\n\n"
    ) + body
    _PROGRESSION_PATH.parent.mkdir(parents=True, exist_ok=True)
    safe_write(_PROGRESSION_PATH, content)
    return content


# ── Helpers ──────────────────────────────────────────────────────────────────


def _count_jsonl_rows(path: Path) -> int:
    if not path.exists():
        return 0
    return sum(1 for line in path.read_text().splitlines() if line.strip())


def _read_final_scores(path: Path) -> list[int]:
    scores: list[int] = []
    if not path.exists():
        return scores
    for line in path.read_text().splitlines():
        if not line.strip():
            continue
        row: dict[str, Any] = json.loads(line)
        os_d_raw = row.get("overall_score")
        if not isinstance(os_d_raw, dict):
            continue
        final_raw = os_d_raw.get("final")  # type: ignore[reportUnknownMemberType]
        if isinstance(final_raw, int | float):
            scores.append(int(final_raw))
    return scores


def _published_concept_ids() -> set[str]:
    if not _OUT_DIR.exists():
        return set()
    return {p.stem for p in _OUT_DIR.glob("*.md")}


def _domain_distribution(path: Path) -> dict[str, int]:
    """Count assets per domain category (A-J prefix on asset_id)."""
    dist: dict[str, int] = {}
    if not path.exists():
        return dist
    for line in path.read_text().splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        asset_id = str(row.get("asset_id") or "")
        domain = asset_id.split("-", maxsplit=1)[0] if "-" in asset_id else "?"
        dist[domain] = dist.get(domain, 0) + 1
    return dist


def _read_run_log_events(run_id: str) -> list[dict[str, Any]]:
    events: list[dict[str, Any]] = []
    if not _RUN_LOG.exists():
        return events
    for line in _RUN_LOG.read_text().splitlines():
        if not line.strip():
            continue
        ev = json.loads(line)
        if ev.get("session_id") == run_id:
            events.append(ev)
    return events


def _sum_run_log_cost(run_id: str) -> float:
    total = 0.0
    for ev in _read_run_log_events(run_id):
        cost = ev.get("cost_usd")
        if isinstance(cost, int | float):
            total += float(cost)
    return total


def _wall_time_per_phase(run_id: str) -> dict[str, float]:
    """Compute wall time per phase from START/DONE events in the run log."""
    starts: dict[str, str] = {}
    durations: dict[str, float] = {}
    for ev in _read_run_log_events(run_id):
        phase = str(ev.get("phase") or "")
        ts = str(ev.get("ts") or "")
        if not phase or not ts:
            continue
        if ev.get("event") == "START":
            starts[phase] = ts
        elif ev.get("event") == "DONE" and phase in starts:
            try:
                t0 = datetime.datetime.fromisoformat(starts[phase])
                t1 = datetime.datetime.fromisoformat(ts)
                durations[phase] = round((t1 - t0).total_seconds(), 1)
            except ValueError:
                continue
    return durations


def _count_key_rotations(run_id: str) -> int:
    return sum(1 for ev in _read_run_log_events(run_id) if ev.get("event") == "BUDGET_EXCEEDED")


def _count_stabilization_queued(run_id: str) -> int:
    return sum(
        1 for ev in _read_run_log_events(run_id) if ev.get("event") == "STABILIZATION_QUEUED"
    )


def _percentile(values: list[int], p: int) -> int:
    if not values:
        return 0
    sorted_v = sorted(values)
    k = (len(sorted_v) - 1) * (p / 100)
    lo = int(k)
    hi = min(lo + 1, len(sorted_v) - 1)
    return round(sorted_v[lo] + (sorted_v[hi] - sorted_v[lo]) * (k - lo))


def _read_timeline() -> list[dict[str, Any]]:
    if not _TIMELINE_PATH.exists():
        return []
    rows: list[dict[str, Any]] = []
    for line in _TIMELINE_PATH.read_text().splitlines():
        if not line.strip():
            continue
        rows.append(json.loads(line))
    return rows


def _build_progression_body(rows: list[dict[str, Any]]) -> str:
    """Markdown body listing recent runs + simple deltas."""
    recent = rows[-10:]
    lines: list[str] = ["## Last 10 Runs\n"]
    lines.append(
        "| ts (UTC) | theme | model | concepts | published | mean score | max score | cost USD |"
    )
    lines.append("|---|---|---|---|---|---|---|---|")
    for r in recent:
        lines.append(
            f"| {str(r.get('ts', ''))[:19]} "
            f"| {str(r.get('theme', ''))[:30]} "
            f"| {str(r.get('model', '')).split('/')[-1][:24]} "
            f"| {r.get('concept_count', 0)} "
            f"| {r.get('concept_published_count', 0)} "
            f"| {r.get('concept_final_score_mean', 0)} "
            f"| {r.get('concept_final_score_max', 0)} "
            f"| {r.get('total_cost_usd_per_run', 0)} |"
        )
    lines.append("")
    if len(rows) >= _DELTA_MIN_RUNS:
        prev = rows[-2]
        cur = rows[-1]
        lines.append("## Delta vs Previous Run\n")
        lines.append("| metric | prev | current | delta |")
        lines.append("|---|---|---|---|")
        for key in (
            "concept_count",
            "concept_published_count",
            "concept_final_score_mean",
            "concept_final_score_max",
            "concepts_passing_85_pure_critic_count",
            "stabilization_patterns_queued",
            "total_cost_usd_per_run",
            "key_rotation_count",
        ):
            p = prev.get(key, 0)
            c = cur.get(key, 0)
            try:
                delta = round(c - p, 4) if isinstance(c, int | float) else "—"
            except (TypeError, ValueError):
                delta = "—"
            lines.append(f"| {key} | {p} | {c} | {delta} |")
        lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    # CLI: `python -m pipeline.metrics` regenerates docs/PROGRESSION.md
    md = regenerate_progression_md()
    print("docs/PROGRESSION.md regenerated.")
    print("---")
    print(md)
