"""scripts/audit_corpus.py — read-only corpus health audit.

Loads the FilmsCorpus and writes a markdown report describing:
  - Total films + per-decade / per-genre histograms
  - IMDb-id coverage
  - Enrichment split (legacy v5 vs v6.0 E3a enriched)
  - Per-field gap histogram (which fields are null or empty across the corpus)
  - Top-N films by worldwide gross (sanity check on the tentpole F0.4 enrichment)

Output: .planning/state/corpus_audit_<YYYY-MM-DD>.md.

No corpus data changes. Pure inspection.

Run:
  uv run python scripts/audit_corpus.py
"""

from __future__ import annotations

import datetime as dt
from collections import Counter
from pathlib import Path

from pipeline.crystallize.corpus import Film, FilmsCorpus

_GROSS_TOP_N = 10
_GENRE_TOP_N = 15
_GAP_BAR_WIDTH = 40


def _decade(year: int | None) -> str:
    if year is None:
        return "(unknown)"
    return f"{(year // 10) * 10}s"


def _bar(fraction: float, width: int = _GAP_BAR_WIDTH) -> str:
    filled = round(fraction * width)
    return "█" * filled + "·" * (width - filled)


def _coverage(films: tuple[Film, ...]) -> dict[str, tuple[int, float]]:
    """For each Film field that may be missing, count non-empty rows."""
    n = len(films)
    if n == 0:
        return {}

    def _present(f: Film, attr: str) -> bool:
        v = getattr(f, attr, None)
        if v is None:
            return False
        if isinstance(v, str):
            return bool(v.strip())
        if isinstance(v, tuple | list):
            return bool(v)
        return True

    fields = (
        "imdb_id",
        "worldwide_gross_usd",
        "domestic_gross_usd",
        "international_gross_usd",
        "budget_usd",
        "distributor",
        "release_year",
        "mpaa",
        "imdb_url",
        "boxofficemojo_url",
        "log_line",
        "tagline",
        "synopsis",
        "domain_tags",
        "mood_palette",
    )
    out: dict[str, tuple[int, float]] = {}
    for field_name in fields:
        present = sum(1 for f in films if _present(f, field_name))
        out[field_name] = (present, present / n)
    return out


def _decade_histogram(films: tuple[Film, ...]) -> list[tuple[str, int]]:
    counts: Counter[str] = Counter(_decade(f.release_year) for f in films)
    return sorted(counts.items(), key=lambda kv: kv[0])


def _genre_histogram(films: tuple[Film, ...]) -> list[tuple[str, int]]:
    counts: Counter[str] = Counter()
    for f in films:
        counts.update(f.genres)
    return counts.most_common(_GENRE_TOP_N)


def _enriched_count(films: tuple[Film, ...]) -> int:
    # A row is "enriched" if it has any prose field populated.
    return sum(1 for f in films if (f.log_line or f.synopsis or f.tagline))


def _top_gross(films: tuple[Film, ...]) -> list[Film]:
    with_gross = [f for f in films if f.worldwide_gross_usd is not None]
    return sorted(with_gross, key=lambda f: f.worldwide_gross_usd or 0.0, reverse=True)[
        :_GROSS_TOP_N
    ]


def _render_summary(films: tuple[Film, ...], root: Path, today: str) -> list[str]:
    n = len(films)
    enriched = _enriched_count(films)
    enriched_line = (
        f"- **Enriched rows** (v6.0 E3a — at least one of log_line/tagline/synopsis): "
        f"{enriched} ({enriched / n:.1%})"
        if n
        else "- **Enriched rows:** (n/a — corpus is empty)"
    )
    return [
        f"# Corpus Health Audit — {today}",
        "",
        "Generated by `scripts/audit_corpus.py`. Read-only diagnostic.",
        "",
        "## Summary",
        "",
        f"- **Total films:** {n}",
        f"- **Corpus root:** `{root}`",
        enriched_line,
        "",
    ]


def _render_coverage(films: tuple[Film, ...]) -> list[str]:
    n = len(films)
    cov = _coverage(films)
    out = ["## Field coverage", "", "| Field | Present | Coverage | Bar |", "|---|---|---|---|"]
    for field_name, (present, frac) in cov.items():
        out.append(f"| `{field_name}` | {present}/{n} | {frac:.1%} | {_bar(frac)} |")
    out.append("")
    return out


def _render_decade_table(films: tuple[Film, ...]) -> list[str]:
    out = ["## Release decade histogram", "", "| Decade | Count |", "|---|---|"]
    for decade, count in _decade_histogram(films):
        out.append(f"| {decade} | {count} |")
    out.append("")
    return out


def _render_genre_table(films: tuple[Film, ...]) -> list[str]:
    out = [f"## Genre histogram (top {_GENRE_TOP_N})", "", "| Genre | Count |", "|---|---|"]
    for genre, count in _genre_histogram(films):
        out.append(f"| {genre} | {count} |")
    out.append("")
    return out


def _render_top_gross(films: tuple[Film, ...]) -> list[str]:
    out = [
        f"## Top {_GROSS_TOP_N} films by worldwide gross",
        "",
        "| Rank | Title | Year | WW gross (USD) |",
        "|---|---|---|---|",
    ]
    for i, f in enumerate(_top_gross(films), start=1):
        gross = f.worldwide_gross_usd or 0.0
        out.append(f"| {i} | {f.title} | {f.release_year or '?'} | ${gross:,.0f} |")
    out.append("")
    return out


_NEXT_ACTIONS: tuple[str, ...] = (
    "## Next-action suggestions",
    "",
    "- **Low-coverage fields below 50% are the operator's call:** any field where",
    "  this audit shows < 50% coverage is either (a) genuinely optional for the",
    "  current pipeline (e.g., `mpaa`, `mood_palette` only matter for downstream",
    "  embedding), or (b) a real backfill task. Decide per field, not all at once.",
    "- **Enrichment gaps:** if `log_line` / `synopsis` < 80%, the C002 novelty",
    "  kill-switch (when wired) will under-fire because the embedding signal is",
    "  noisy. Top up via `scripts/fetch_tmdb_enrichment.py` against the slugs that",
    "  lack prose.",
    "- **Decade skew:** if the histogram clusters in one decade, comp matching will",
    "  over-favour that era. The F0.4 tentpole enrichment was meant to lift",
    "  ceiling for recent decades — check the histogram matches the operator's",
    "  expected era weighting.",
    "",
)


def render(corpus: FilmsCorpus) -> str:
    today = dt.date.today().isoformat()
    out: list[str] = []
    out.extend(_render_summary(corpus.films, corpus.root, today))
    out.extend(_render_coverage(corpus.films))
    out.extend(_render_decade_table(corpus.films))
    out.extend(_render_genre_table(corpus.films))
    out.extend(_render_top_gross(corpus.films))
    out.extend(_NEXT_ACTIONS)
    return "\n".join(out) + "\n"


def main() -> int:
    corpus = FilmsCorpus.load()
    out_dir = Path(".planning/state")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"corpus_audit_{dt.date.today().isoformat()}.md"
    out_path.write_text(render(corpus), encoding="utf-8")
    print(f"Wrote {out_path} ({len(corpus.films)} films audited)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
